backend/accounts/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view

app_name = "accounts"

urlpatterns = [
        path('login/', login_view, name='login'),
        path('register/', register_view, name='register'),
        path('logout/', logout_view, name='logout'),
]

backend/api/urls.py
from django.urls import path, include
from .views import PostList, PostDetail, CommentList

app_name = "api"

urlpatterns = [
        path('<int:pk>/', PostDetail.as_view()),
        path('comments/', CommentList.as_view()),
        path('', PostList.as_view()),
        #path('', post_list_create_api_view, name='postlist'),
        path('api-auth/', include('rest_framework.urls')), # new
]

backend/blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from frontpage.views import front_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', front_view, name='frontpage'),
    path('', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/post/urls.py
from django.urls import path
from .views import post_create, post_detail

app_name = "posts"

urlpatterns = [
        path('create/', post_create, name='create'),
        path('<int:id>/', post_detail, name='detail'),
]

backend/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Django 2.2 Simple Blog Post">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet" type="text/css" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" crossorigin="anonymous">

    <title>Django Blog Tutorial</title>

  </head>
  <body>
    {% include 'header.html' %}
    

    <main class="container">
      {% include 'messages.html' %}
        {% block body %}
        {% endblock %}

        {% include 'footer.html' %}
    </main>
    <!-- Jquery library -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}" crossorigin="anonymous"></script>
    <!-- Bootstrap core js -->
    <script src="{% static 'js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
  </body>
</html>

backend/templates/footer.html
    <footer class="pt-3 mt-4 text-muted border-top text-center">
        &copy; 2021 - 2022 Django 2.2, DRF and Vue 2
    </footer>

backend/templates/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <a class="navbar-brand p-0 me-1" href="{% url 'frontpage' %}" style="margin-top:-5px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" class="bi bi-code-slash" viewBox="0 0 16 16">
            <path d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294l4-13zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0zm6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0z"/>
          </svg>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'frontpage' %}">Blog Editor</a>
          </li>
          
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a href ="{% url 'posts:create' %}" class="nav-link">Create new post</a>
            {% endif %}
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <ul class="nav">

          {% if not request.user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'accounts:login' %}" class="btn btn-outline-light me-2">Login</a></li>
            <li class="nav-item"><a href="{% url 'accounts:register' %}" class="btn btn-warning">Sign up</a></li>
          {% else %}
            <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>

backend/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="bg-light p-5 rounded">
    

      <h1>Django Blog Tutorial</h1>
      <p class="lead">A Simple Blog App Using Django-2.2 for back-end and Vue.js for front-end.</p>
      {% if user.is_authenticated %}
        <p class="lead">Hi {{ user.username }}!</p>
        {% else %}
        <p class="lead">You are not logged in</p>
       {% endif %}
      <a class="btn btn-lg btn-primary" href="http://djangoproject.com" role="button">
          View more &raquo;</a>
    </div>
{% endblock %}

backend/templates/messages.html
{% if messages %}
    {% for message in messages %}
         <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    {% endfor %}
{% endif %}